acre:
  cep: '69921-380'
  logradouro: "Rua Raimundo Farias"
  complemento: ""
  bairro: "Montanhês"
  localidade: "Rio Branco"
  uf: "AC"
  ibge: "1200401"
  gia: ""
  ddd: "67"
  siafi: "0139"
alagoas: 
  cep: '57015-215'
  logradouro: "Travessa São João"
  complemento: ""
  bairro: "Vergel do Lago"
  localidade: "Maceió"
  uf: "AL"
  ibge: "2704302"
  gia: ""
  ddd: "82"
  siafi: "2785"
amazonas:
  cep: '69041-045'
  logradouro: "Rua Branco Silva"
  complemento: ""
  bairro: "Tarumã"
  localidade: "Manaus"
  uf: "AM"
  ibge: "1302603"
  gia: ""
  ddd: "92"
  siafi: "0255"
amapa:
  cep: '68905-150'
  logradouro: "Passagem Flor de Lis"
  complemento: ""
  bairro: "Cidade Nova"
  localidade: "Macapá"
  uf: "AP"
  ibge: "1600303"
  gia: ""
  ddd: "96"
  siafi: "0605"
bahia:
  cep: '45601-164'
  logradouro: "Rua da Jaqueira"
  complemento: ""
  bairro: "Lomanto Júnior"
  localidade: "Itabuna"
  uf: "BA"
  ibge: "2914802"
  gia: ""
  ddd: "73"
  siafi: "3597"
ceara:
  cep: '63901-185'
  logradouro: "Rua 14"
  complemento: "(Lot Renascer II)"
  bairro: "Planalto Renascer"
  localidade: "Quixadá"
  uf: "CE"
  ibge: "2311306"
  gia: ""
  ddd: "88"
  siafi: "1527"
distrito_federal:
  cep: '71930-750'
  logradouro: "Quadra 209"
  complemento: ""
  bairro: "Sul (Águas Claras)"
  localidade: "Brasília"
  uf: "DF"
  ibge: "5300108"
  gia: ""
  ddd: "61"
  siafi: "9701"
espirito_santo:
  cep: '29705-231'
  logradouro: "Rua José Monteiro de Souza"
  complemento: ""
  bairro: "Carlos Germano Naumann"
  localidade: "Colatina"
  uf: "ES"
  ibge: "3201506"
  gia: ""
  ddd: "27"
  siafi: "5629"
goias:
  cep: '72853-272'
  logradouro: "Quadra 272"
  complemento: ""
  bairro: "Parque Estrela Dalva IX"
  localidade: "Luziânia"
  uf: "GO"
  ibge: "5212501"
  gia: ""
  ddd: "61"
  siafi: "9445"
maranhao:
  cep: '65604-645'
  logradouro: "Rua Dezesseis"
  complemento: "(COHAB)"
  bairro: "Nova Caxias"
  localidade: "Caxias"
  uf: "MA"
  ibge: "2103000"
  gia: ""
  ddd: "99"
  siafi: "0757"
minas_gerais:
  cep: '31170-680'
  logradouro: "Rua Lincoln"
  complemento: ""
  bairro: "União"
  localidade: "Belo Horizonte"
  uf: "MG"
  ibge: "3106200"
  gia: ""
  ddd: "31"
  siafi: "4123"
mato_grosso_do_sul:
  cep: '79070-534'
  logradouro: "Rua Parauna"
  complemento: ""
  bairro: "Porto Galo"
  localidade: "Campo Grande"
  uf: "MS"
  ibge: "5002704"
  gia: ""
  ddd: "67"
  siafi: "9051"
mato_grosso:
  cep: '78725-382'
  logradouro: "Rua Cinco"
  complemento: ""
  bairro: "Jardim Dom Bosco"
  localidade: "Rondonópolis"
  uf: "MT"
  ibge: "5107602"
  gia: ""
  ddd: "66"
  siafi: "9151"
para:
  cep: '67146-020'
  logradouro: "Quadra Vinte"
  complemento: "(Cj Roraima-Amapá)"
  bairro: "Maguari"
  localidade: "Ananindeua"
  uf: "PA"
  ibge: "1500800"
  gia: ""
  ddd: "91"
  siafi: "0415"
paraiba:
  cep: '58011-210'
  logradouro: "Rua Barão de Maraú"
  complemento: ""
  bairro: "Varadouro"
  localidade: "João Pessoa"
  uf: "PB"
  ibge: "2507507"
  gia: ""
  ddd: "83"
  siafi: "2051"
pernambuco:
  cep: '55192-390'
  logradouro: "Rua José Bernardino Gomes"
  complemento: ""
  bairro: "Bairro Novo"
  localidade: "Santa Cruz do Capibaribe"
  uf: "PE"
  ibge: "2612505"
  gia: ""
  ddd: "81"
  siafi: "2549"
piaui:
  cep: '64207-093'
  logradouro: "Conjunto Padre Anchieta"
  complemento: ""
  bairro: "Frei Higino"
  localidade: "Parnaíba"
  uf: "PI"
  ibge: "2207702"
  gia: ""
  ddd: "86"
  siafi: "1153"
parana:
  cep: '84043-265'
  logradouro: "Rua Tiriva"
  complemento: ""
  bairro: "Colônia Dona Luíza"
  localidade: "Ponta Grossa"
  uf: "PR"
  ibge: "4119905"
  gia: ""
  ddd: "42"
  siafi: "7777"
rio_de_janeiro:
  cep: '24730-420'
  logradouro: "Estrada Amendoeira"
  complemento: ""
  bairro: "Raul Veiga"
  localidade: "São Gonçalo"
  uf: "RJ"
  ibge: "3304904"
  gia: ""
  ddd: "21"
  siafi: "5897"
rio_grande_do_norte:
  cep: '59065-760'
  logradouro: "Rua Francisco Mignone"
  complemento: ""
  bairro: "Candelária"
  localidade: "Natal"
  uf: "RN"
  ibge: "2408102"
  gia: ""
  ddd: "84"
  siafi: "1761"
rio_grande_do_sul:
  cep: '91215-085'
  logradouro: "Rua Israel Wolf"
  complemento: ""
  bairro: "Jardim Itu"
  localidade: "Porto Alegre"
  uf: "RS"
  ibge: "4314902"
  gia: ""
  ddd: "51"
  siafi: "8801"
rondonia:
  cep: '76913-697'
  logradouro: "Rua Júlio Prestes"
  complemento: "de 995 a 1135 - lado ímpar"
  bairro: "Riachuelo"
  localidade: "Ji-Paraná"
  uf: "RO"
  ibge: "1100122"
  gia: ""
  ddd: "69"
  siafi: "0005"
roraima:
  cep: '69309-409'
  logradouro: "Rua Industrial 2"
  complemento: ""
  bairro: "Pricumã"
  localidade: "Boa Vista"
  uf: "RR"
  ibge: "1400100"
  gia: ""
  ddd: "95"
  siafi: "0301"
santa_catarina:
  cep: '89260-570'
  logradouro: "Rua Alfredo Hanemann"
  complemento: ""
  bairro: "Barra do Rio Cerro"
  localidade: "Jaraguá do Sul"
  uf: "SC"
  ibge: "4208906"
  gia: ""
  ddd: "47"
  siafi: "8175"
sergipe:
  cep: '49047-070'
  logradouro: "Rua Carlos Gomes"
  complemento: ""
  bairro: "Ponto Novo"
  localidade: "Aracaju"
  uf: "SE"
  ibge: "2800308"
  gia: ""
  ddd: "79"
  siafi: "3105"
sao_paulo:
  cep: '01001-000'
  logradouro: "Praça da Sé"
  complemento: "lado ímpar"
  bairro: "Sé"
  localidade: "São Paulo"
  uf: "SP"
  ibge: "3550308"
  gia: "1004"
  ddd: "11"
  siafi: "7107"
