name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set IMAGE_TAG
      id: set_image_tag
      run: echo "::set-output name=IMAGE_TAG::my-image-name:$(date +%s)"

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ steps.set_image_tag.outputs.IMAGE_TAG }}

    - name: Run tests
      run: |
        docker run ${{ steps.set_image_tag.outputs.IMAGE_TAG }}
