name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create IMAGE_TAG environment file
      run: echo "IMAGE_TAG=my-image-name:$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Run tests
      run: |
        docker run ${{ env.IMAGE_TAG }}
